import {
  AgentOutput,
  RequirementAnalyzerOutput,
  SystemDesignOutput,
  TechStackOutput,
  DiagramGeneratorOutput,
  APIDesignOutput,
  CostEstimationOutput,
  DeploymentStrategyOutput,
  FailureModeAnalyzerOutput,
} from '../core/contracts';

/**
 * Generates a Startup-Premium System Design Document (SDD).
 */
export class DocumentationGenerator {
  static generateMarkdown(project: any, latestVersion: any): string {
    const sections: string[] = [];
    const outputs = this.mapOutputs(latestVersion.agentOutputs);

    // Header Section
    sections.push(this.generateHeader(project, latestVersion));

    // Table of Contents
    sections.push(this.generateTOC());

    // 1. Executive Summary
    sections.push(`## 1. Executive Summary
${project.description || 'This document outlines the architectural blueprint and technical specifications for the system as proposed by Fame Systemly.'}`);

    // 2. Requirements Analysis
    if (outputs.requirement_analyzer) {
      sections.push(
        this.generateRequirementsSection(outputs.requirement_analyzer as RequirementAnalyzerOutput)
      );
    }

    // 3. System Architecture
    if (outputs.system_design) {
      sections.push(this.generateArchitectureSection(outputs.system_design as SystemDesignOutput));
    }

    // 4. Data Flow & Visualizations
    if (outputs.diagram_generator) {
      sections.push(
        this.generateDiagramsSection(outputs.diagram_generator as DiagramGeneratorOutput)
      );
    }

    // 5. Technology Stack
    if (outputs.tech_stack) {
      sections.push(this.generateTechStackSection(outputs.tech_stack as TechStackOutput));
    }

    // 6. API Specifications
    if (outputs.api_design) {
      sections.push(this.generateApiDesignSection(outputs.api_design as APIDesignOutput));
    }

    // 7. Cost & Infrastructure
    if (outputs.cost_estimation) {
      sections.push(this.generateCostSection(outputs.cost_estimation as CostEstimationOutput));
    }

    // 8. Deployment & CI/CD
    if (outputs.deployment_strategy) {
      sections.push(
        this.generateDeploymentSection(outputs.deployment_strategy as DeploymentStrategyOutput)
      );
    }

    // 9. Reliability & Failure Modes
    if (outputs.failure_mode_analyzer) {
      sections.push(
        this.generateFailureSection(outputs.failure_mode_analyzer as FailureModeAnalyzerOutput)
      );
    }

    return sections.join('\n\n---\n\n');
  }

  private static generateTOC(): string {
    return `## Table of Contents
1. [Executive Summary](#1-executive-summary)
2. [Requirements & Constraints](#2-requirements--constraints)
3. [System Architecture](#3-system-architecture)
4. [Visualizations](#4-visualizations)
5. [Technology Stack](#5-technology-stack-selection)
6. [API Design Spec](#6-api-design-spec)
7. [Cost & Infrastructure](#7-cost--infrastructure-projection)
8. [Deployment Strategy](#8-deployment--cicd-strategy)
9. [Reliability & Failure Modes](#9-reliability--failure-modes)`;
  }

  private static mapOutputs(agentOutputs: AgentOutput[]): Record<string, unknown> {
    const map: Record<string, unknown> = {};
    for (const out of agentOutputs) {
      if (out.status === 'completed' && out.output) {
        map[out.agentType] = out.output;
      }
    }
    return map;
  }

  private static generateHeader(project: any, version: any): string {
    return `# System Design: ${project.title}
> **Generated by Systemly** • v${version.version}.0 • ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}

---

| Project Metadata | Detail |
| :--- | :--- |
| **Project ID** | \`${project.id}\` |
| **Status** | \`${version.status.toUpperCase()}\` |
| **Base Prompt** | *${version.prompt.length > 100 ? version.prompt.substring(0, 100) + '...' : version.prompt}* |
`;
  }

  private static generateRequirementsSection(data: RequirementAnalyzerOutput): string {
    const functional = data.functionalRequirements.map((req) => `- [ ] ${req}`).join('\n');
    const nonFunctional = data.nonFunctionalRequirements.map((req) => `- [x] ${req}`).join('\n');

    return `## 2. Requirements & Constraints

### 🎯 Functional Requirements
${functional}

### ⚖️ Non-Functional Requirements
${nonFunctional}

### 💡 Core Assumptions
${data.assumptions.map((item) => `- ${item}`).join('\n')}

### 🛠️ Clarifying Decisions
> These decisions were made to resolve architectural ambiguities during analysis.
${data.clarifyingDecisions.map((item) => `- ${item}`).join('\n')}
`;
  }

  private static generateArchitectureSection(data: SystemDesignOutput): string {
    const components = data.highLevelComponents
      .map(
        (c) => `#### 🏗️ ${c.name}
> ${c.description}
- **Primary Responsibilities:** ${c.responsibilities.join(', ')}`
      )
      .join('\n\n');

    return `## 3. System Architecture

### 🧩 High-Level Components
${components}

### ↔️ Service Communication
${data.serviceBoundaries.map((s) => `- **${s.service}**: ${s.description}`).join('\n')}

### 🚀 Scaling Strategy
- **Horizontal:** ${data.scalingStrategy.horizontalScaling.join(', ')}
- **Vertical:** ${data.scalingStrategy.verticalScaling.join(', ')}
- **Caching:** ${data.scalingStrategy.cachingStrategy}
- **Database:** ${data.scalingStrategy.databaseScaling}
`;
  }

  private static generateDiagramsSection(data: DiagramGeneratorOutput): string {
    return `## 4. Visualizations

### 📐 High-Level Topology
\`\`\`mermaid
${data.highLevelSystem}
\`\`\`

### 🌊 Request Sequence Flow
\`\`\`mermaid
${data.requestFlow}
\`\`\`

### 📈 Scaling Architecture
\`\`\`mermaid
${data.scalingView}
\`\`\`
`;
  }

  private static generateTechStackSection(data: TechStackOutput): string {
    return `## 5. Technology Stack Selection

| Layer | Technology | Justification |
| :--- | :--- | :--- |
| **Frontend** | ${data.frontend.framework} | ${data.frontend.justification} |
| **Backend** | ${data.backend.framework} (${data.backend.runtime}) | ${data.backend.justification} |
| **Primary DB** | ${data.database.primary} | ${data.database.justification} |
| **Caching** | ${data.database.caching} | Integrated for low-latency state. |
| **Messaging** | ${data.messaging.queue} | ${data.messaging.justification} |
| **Infrastructure** | ${data.infrastructure.compute} | ${data.infrastructure.justification} |
`;
  }

  private static generateApiDesignSection(data: APIDesignOutput): string {
    const endpoints = data.endpoints
      .map((e) => `| \`${e.method}\` | \`${e.path}\` | ${e.description} | ${e.authentication} |`)
      .join('\n');

    return `## 6. API Design Spec

**Versioning Policy:** \`${data.apiVersioning}\`
**Error Handling:** ${data.errorHandling}

### 🛣️ Primary Endpoints
| Method | Path | Description | Access |
| :--- | :--- | :--- | :--- |
${endpoints}
`;
  }

  private static generateCostSection(data: CostEstimationOutput): string {
    return `## 7. Cost & Infrastructure Projection

### 💰 Monthly Burn Estimate
| Resource | Cost (USD) | Unit |
| :--- | :--- | :--- |
| **Compute** | $${data.infrastructure.compute.estimatedMonthly} | Avg / Month |
| **Storage** | $${data.infrastructure.storage.estimatedMonthly} | Per GB Tier |
| **Networking** | $${data.infrastructure.networking.estimatedMonthly} | Traffic Bound |
| **Third-Party** | $${data.infrastructure.thirdParty.estimatedMonthly} | Managed APIs |
| **Total Monthly** | **$${data.totalMonthly}** | **Total Core Opex** |

### 📈 TGU Scaling (Total Growth Utility)
- **100k Monthly Users:** ~$${data.scalingProjection.at100kUsers}/mo
- **1M Monthly Users:** ~$${data.scalingProjection.at1mUsers}/mo
`;
  }

  private static generateDeploymentSection(data: DeploymentStrategyOutput): string {
    return `## 8. Deployment & CI/CD Strategy

### 🌍 Infrastructure Model
- **Model:** \`${data.deploymentModel}\`
- **Primary CI/CD:** \`${data.ciCd.pipeline}\`

### 🏗️ Environmental Configuration
${data.environments.map((e) => `- **${e.name}**: ${e.purpose} (using ${e.infrastructure})`).join('\n')}

### 🛠️ Observability & Rollback
- **Monitoring Tools:** ${data.monitoring.join(', ')}
- **Rollback Policy:** ${data.rollbackStrategy}
`;
  }

  private static generateFailureSection(data: FailureModeAnalyzerOutput): string {
    const scenarios = data.failureScenarios
      .map(
        (f) => `#### 🚨 ${f.scenario}
- **Impact:** \`${f.impact.toUpperCase()}\` (Prob: \`${f.probability}\`)
- **Description:** ${f.description}
- **Mitigation:** ${f.mitigation.join(', ')}`
      )
      .join('\n\n');

    return `## 9. Reliability & Failure Modes

**Core Resilience Score:** \`${data.resilienceScore}/100\`

### 🛡️ Risk Assessment
${scenarios}

### 🔍 Single Points of Failure (SPOF)
${data.singlePointsOfFailure.map((item) => `- ${item}`).join('\n')}
`;
  }
}
