import { APIDesignOutput } from '../core/contracts';

export class OpenApiGenerator {
  static generate(projectTitle: string, apiDesign: APIDesignOutput): object {
    const spec: any = {
      openapi: '3.0.0',
      info: {
        title: projectTitle,
        description:
          apiDesign.documentation ||
          `API Specification for ${projectTitle}\n\nGenerated by AI Design Orchestrator.`,
        version: apiDesign.apiVersioning || '1.0.0',
        contact: {
          name: 'DevOps Team',
          email: 'support@example.com',
        },
      },
      servers: [
        {
          url: 'https://api.production.example.com/v1',
          description: 'Production Server',
        },
        {
          url: 'https://api.staging.example.com/v1',
          description: 'Staging Server',
        },
      ],
      paths: {},
      components: {
        schemas: {
          Error: {
            type: 'object',
            properties: {
              code: { type: 'string' },
              message: { type: 'string' },
            },
          },
        },
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
          apiKeyAuth: {
            type: 'apiKey',
            in: 'header',
            name: 'X-API-KEY',
          },
        },
      },
    };

    apiDesign.endpoints.forEach((endpoint) => {
      const path = endpoint.path.startsWith('/') ? endpoint.path : `/${endpoint.path}`;
      const method = endpoint.method.toLowerCase();

      if (!spec.paths[path]) {
        spec.paths[path] = {};
      }

      const operation: any = {
        tags: [this.inferTag(path)],
        summary: endpoint.description,
        description: endpoint.description,
        responses: {
          '200': {
            description: 'Success',
          },
          '400': {
            description: 'Bad Request',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
          },
          '401': {
            description: 'Unauthorized access',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
          },
          '500': {
            description: 'Internal Server Error',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
          },
        },
      };

      // Security Integration
      if (
        endpoint.authentication &&
        !['None', 'Public', 'none'].includes(endpoint.authentication)
      ) {
        operation.security = [{ bearerAuth: [] }];
      }

      // Branding/Metadata
      if (endpoint.rateLimiting) {
        operation['x-rate-limit'] = endpoint.rateLimiting;
      }

      // Request Body
      if (endpoint.requestBody) {
        operation.requestBody = {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                description: endpoint.requestBody.schema,
                example: endpoint.requestBody.example || {},
              },
            },
          },
        };
      }

      // Response Body (Mapped to 200/201 depending on method)
      const successCode = method === 'post' ? '201' : '200';
      if (operation.responses['200'] && successCode === '201') {
        operation.responses['201'] = operation.responses['200'];
        delete operation.responses['200'];
      }

      if (endpoint.responseBody) {
        operation.responses[successCode].content = {
          'application/json': {
            schema: {
              type: 'object',
              description: endpoint.responseBody.schema,
              example: endpoint.responseBody.example || {},
            },
          },
        };
      }

      spec.paths[path][method] = operation;
    });

    return spec;
  }

  private static inferTag(path: string): string {
    const parts = path.split('/').filter(Boolean);
    if (parts.length > 0) {
      return parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
    }
    return 'Default';
  }
}
